[project]
name = "aoc2024"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
packages = [
    { include = "src" }
]
dependencies = [
    "numpy>=2.0.2",
    "polars>=1.16.0",
]
